### ISSUE TITLE
deployyyyyyyyyyyyyyyyyyyy

### ISSUE THREAD

**Issue by scp-koakutsu** [koachan777/rakuraku_input#90]
deployyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyiyiyiiyiyiyyiyiyiyayyayyayaayyayayyayayaayyayayyayayyayayayyyaayyayayayyayayayayyayayya

**Comment by itsutose** [comment]
MySQLのアプリケーションを立ち上げた時の初期のデータベースの様子みたいなのを記述していただければ，僕のほうでもお助けできるかもしれません．

**Comment by scp-koakutsu** [comment]
もしできなかった場合は、立ち上げてから管理者画面で系統、水槽とかを手動でちまちま入力します。。

**Comment by yume-69** [comment]
コメントの温度差えぐいですね
